### ISSUE TITLE
src/android/CordovaMethodThread.java File not found

### ISSUE THREAD

**Issue by DeepakNatraj** [chemerisuk/cordova-support-android-plugin#2]
File CordovaMethodThread.java is missing in src/android. But it has been used in plugin.xml

**Comment by chemerisuk** [comment]
Thank you, published in v0.4.1

**Comment by DeepakNatraj** [comment]
Can you also change the version in https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/blob/master/plugin.xml

**Comment by chemerisuk** [comment]
It uses `~0.4.0` that matches 0.4.1 as well
